.TH CMatrix 1 "Tue Dec 8 2020"
.SH NAME
CMatrix
.SH SYNOPSIS
.B cmatrix
[FLAGS] [OPTIONS]
.SH DESCRIPTION
Shows a scrolling 'Matrix' like screen in Linux
.SS FLAGS
.TP
.B "\-a"
Asynchronous scroll
.TP
.B "\-b"
Bold characters on
.TP
.B "\-B"
All bold characters (overrides \-b)
.TP
.B "\-c"
Use Japanese characters as seen in the original matrix. Requires appropriate fonts
.TP
.B "\-f"
Force the linux $TERM type to be on
.TP
.B "\-h, \-?"
Print usage and exit
.TP
.B "\-k"
Characters in each stream can randomly change (only without \-o)
.TP
.B "\-l"
Use matrix console font (TTY ONLY!)
.TP
.B "\-L"
Lock mode (must be closed from another terminal)
.TP
.B "\-m"
"Lambda" mode, every character becomes a lambda
.TP
.B "\-n"
No bold characters (overrides \-b and \-B, default behaviour)
.TP
.B "\-o"
Use old-style scrolling
.TP
.B "\-r"
Rainbow mode
.TP
.B "\-s"
"Screensaver" mode, exits on first keystroke
.TP
.B "\-v"
Print version information and exit
.TP
.B "\-x"
X window mode, use if your xterm is using mtx.pcf
.SS OPTIONS
.TP
.B "\-C color"
Use this color for matrix (default green). 
Valid colors are green, red, blue, white, yellow, cyan, magenta and black.
.TP
.B "\-M message"
Prints your message in the center of the screen. Overrides \-L's default message
.TP
.B "\-t tty"
Set tty to use
.TP
.B "\-u delay"
Screen update delay 0 - 9, default 4
.SS USAGE
The following keystrokes are available during execution (unavailable in
\-s mode)
.TP
.B "a"
Toggle asynchronous scroll
.TP
.B "b"
Random bold characters
.TP
.B "B"
All bold characters
.TP
.B "n"
Turn off bold characters
.TP
.B "0\-9"
Adjust update speed
.TP
Change the color of the matrix to the corresponding color:
.RS
.IP "!"
red
.IP "@"
green
.IP "#"
yellow
.IP "$"
blue
.IP "%"
magenta
.IP "^"
cyan
.IP "&"
white
.IP ")"
black
.RE
.TP
.B "q"
Quit the program
.SH BUGS
This program is very CPU intensive.  Don't be surprised if it eats up over
40% of your CPU at times.
.SH HOMEPAGE
http://www.github.com/abishekvashok/cmatrix
